INSERT INTO role (id, title, salary, department_id) VALUES
                                                    (1, 'Chief Financial Officer', 350000, 1),
                                                    (2, 'Controller', 225000, 1),
                                                    (3, 'Auditor', 150000, 1),
                                                    (4, 'Chief Sales Officer', 350000, 2),
                                                    (5, 'Vice President of Sales', 225000, 2),
                                                    (6, 'Sales Representative', 125000, 2),
                                                    (7, 'Chief Marketing Officer', 350000, 3),
                                                    (8, 'Director of Marketing', 225000, 3),
                                                    (9, 'Marketing Manager', 120000, 3),
                                                    (10, 'Chief Technology Officer', 350000, 4),
                                                    (11, 'Vice President of Development', 250000, 4),
                                                    (12, 'Software Development Manager', 175000, 4),
                                                    (13, 'Lead Developer', 160000, 4),
                                                    (14, 'Senior Software Developer', 140000, 4),
                                                    (15, 'Software Developer', 120000, 4),
                                                    (16, 'Chief Product Officer', 350000, 5),
                                                    (17, 'Vice President of Product', 250000, 5),
                                                    (18, 'Product Owner', 175000, 5),
                                                    (19, 'Product Manager', 150000, 5),
                                                    (20, 'Chief Human Resources Officer', 350000, 6),
                                                    (21, 'Human Resources Manager', 200000, 6),
                                                    (22, 'Human Resources Assistant', 100000, 6);